name: change-channel-name

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  TOOLCHAIN: stable

jobs:
  change-channel-name:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: update rust
      run: rustup update ${{ env.TOOLCHAIN }} && rustup default ${{ env.TOOLCHAIN }}
    - name: Configure Dependency Caching
      uses: Swatinem/rust-cache@v2
    - name: run
      run: cargo run 